### ISSUE TITLE
401

### ISSUE THREAD

**Issue by shuerhome** [woocommerce/pinterest-for-woocommerce#1000]
{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

**Comment by budzanowski** [comment]
@shuerhome Hi!

Thank you for creating this issue.

Could you please add a bit more context regarding the error string that you have pasted?

- When it happens?
- What is not working?
- Is this found in logs or browser console?
- Which version of Pinterest plugin, WooCommerce and WordPress are you using?

Any additional information will be very helpful because without additional context we can't really know what is going on.

I am more than happy to answer question if you have any!

Thanks!

**Comment by shuerhome** [comment]
Everytime when I connect with pinterest, it will be failed, and the code as follow:

{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

[cid:25b50b0a-0e82-4eb7-a670-80e64af092ed]
________________________________

**Comment by message-dimke** [comment]
Hello, @shuerhome !

Could you tell me more about your setup. Do you have any security plugins installed? They may block WordPress REST API.

**Comment by nima-karimi** [comment]
@shuerhome Closing this as we haven't heard back from you in a while. If you're still experiencing this issue, feel free to start a discussion on [WordPress.org Pinterest for WooCommerce forum](https://wordpress.org/support/plugin/pinterest-for-woocommerce/). Our support engineers are there to help out. If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).
