### ISSUE TITLE
When Merchant change the Advertiser on "Connection" tab, the Tracking conversion is still sent to the previous Advertiser.

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#144]
### Describe the bug:
If a Merchant wants to change the Advertiser on the "Connection" tab of the settings page, The tracking conversion is still being sent to the previous Advertiser.

### Steps to reproduce:
1. Install Pinterest Plugin on a fresh WP+Woo site
2. do the onboarding with a merchant that has 2 or more advertisers and select 1 o them 
3. navigate through the site to send the tracking conversion to the Pinterest account.
4. go to the "Connection" tab on the Settings page of Pinterest plugin and change Advertiser
5. Navigate through the site to send the tracking conversion to the Pinterest account.

#### Expected behavior
Tracking conversion should be sent to the selected Advertiser

#### Actual behavior
Tracking conversion is always sent to the first selected Advertiser.

**Comment by findingsimple** [comment]
@msaggiorato I'm unassigning you, going to assume your not still working on it

**Comment by ecgan** [comment]
I tested this issue with the latest `develop` branch version (commit 5a8d2a9ff1b0fabbf5c33500d2ad0daaba81162e), I don't see this issue happening. I have two advertiser accounts, each having one tracking tag. When I change the advertiser account and tracking tag and save the settings, I can see the `tid` value is updated and fired correctly in the storefront.  Below are the screenshots showing the two `tid` values fired from my storefront product page in browser dev tools:

![image](https://user-images.githubusercontent.com/417342/135521602-bda6dda4-fa23-4fa3-ad80-af1e55bf82fe.png)

![image](https://user-images.githubusercontent.com/417342/135521752-0728f02f-2205-41a5-b72f-7d8c71130d07.png)

@ChristianAF @jamesman11 , I'm going to close this issue now. If you can try this out with a newer build and this issue is still happening, please reopen this issue, and let me know if I'm missing something. 🙏
