### ISSUE TITLE
Actions should be removed/cancelled on disconnect, deactivation & catalog disable

### ISSUE THREAD

**Issue by haszari** [woocommerce/pinterest-for-woocommerce#166]
### Describe the bug:
There's a scheduled action (`WooCommerce > Status > Scheduled Actions`) for registering and generating the feed file (and maybe other feed stuff).

If the merchant disconnects from Pinterest, all feed-related code should stop (as I understand it). However, the action continues to run:

<img width="1800" alt="Screen Shot 2021-08-19 at 10 01 49 AM" src="https://user-images.githubusercontent.com/4167300/129978301-94877512-7abf-4e82-8bd1-b32ef12ee5ec.png">

Note also there are two actions in the table. Is this intended? Seems like a bug.

### Steps to reproduce:
1. Onboard and enable product sync.
2. View the `Pending` actions in `WooCommerce > Status > Scheduled Actions` and search for `pinterest`.
3. Disconnect from Pinterest.

#### Expected behavior
- The actions should be removed/cancelled if user does any of the following:
  - disconnects from Pinterest
  - deactivates or uninstalls Pinterest plugin
  - disables catalog sync.
- Ideally only one scheduled/recurring action. If two are needed, give them different hook names and make it clear how they relate.

In general, if catalog sync is not active, no code relating to it should run.

#### Actual behavior
- 2x recurring actions that look the same.
- Actions continue to run when user has disconnected their store from Pinterest.

**Comment by findingsimple** [comment]
The team has been unable to recreate the 2x or 3x actions as [indicated in thread here](https://github.com/woocommerce/pinterest-for-woocommerce/pull/217#issuecomment-934412913) and believe this was most likely a result of https://github.com/woocommerce/pinterest-for-woocommerce/issues/192 which was fixed in https://github.com/woocommerce/pinterest-for-woocommerce/pull/201

#217 addresses the expected behavior of canceling jobs on account disconnect

**Comment by findingsimple** [comment]
I believe the remaining items to investigate are

> The actions should be removed/cancelled if user does any of the following: ...
> deactivates or uninstalls Pinterest plugin
> disables catalog sync.
