### ISSUE TITLE
Catalog ingestion failing for merchants who used the Premmerce plugin

### ISSUE THREAD

**Issue by wjia88** [woocommerce/pinterest-for-woocommerce#211]
### Describe the bug:

Some users (2/10) managed to complete the setup flow successfully, however, when interviewed several days later, their catalog status still stated “Feed ingestion will start shortly” on the Catalog page of the integration. It is worth noting that both users were previously using the Premmerce plugin, which may have been a contributing factor to this error. This bug is currently under investigation but appears to be related to failure with one of the following methods in the code get_merchant or maybe_create_merchant.

<img width="919" alt="Screen Shot 2021-09-13 at 4 04 12 PM" src="https://user-images.githubusercontent.com/81649037/135351317-68faef2e-2d02-40cf-9e2b-3026ce8a12af.png">

<img width="914" alt="Screen Shot 2021-09-13 at 4 04 47 PM" src="https://user-images.githubusercontent.com/81649037/135351327-ec72da6c-dac3-442b-893e-59b7a77332c7.png">

Logs from website user:

[pinterest plugin logs.pdf](https://github.com/woocommerce/pinterest-for-woocommerce/files/7255159/pinterest.plugin.logs.pdf)

[pinterest logs 2.pdf](https://github.com/woocommerce/pinterest-for-woocommerce/files/7255158/pinterest.logs.2.pdf)

This issue was present in beta.1 build. 

Reason: When merchant with previously created feed profile tries to connect from Woo plugin, feed profile update call fails with error: 
_2021-09-27T04:34:02+00:00 ERROR Error Processing Request: Invalid parameters_

We checked request / response logs and error response is 

```
{
  "message_detail": "To change your country or locale, delete this feed and upload it again.",
  "error": {
    "message": "To change your country or locale, delete this feed and upload it again."
  },
  "code": 1,
  "data": null,
  "message": "Invalid parameters.",
  "endpoint_name": "v3_update_product_pin_feed_profile",
  "st atus": "failure"
}
```

Issue country or locale were set in update request thats why request was failing

Issue was fixed in commit where country and locale were unset in update feed profile request. 
https://github.com/woocommerce/pinterest-for-woocommerce/commit/a2b8fe20d7b79cc2d09e056013b0f10a9c678dd0 

**Changes required:**

1.  Error logging : Can we change the error logging to log message_detail and message both?
2. Updating existing feed profile which are not created from Woo plugin is dangerous since it may cause confusion and undesired result.  On pinterest side we have the info on who created the feed profile which we can expose so that Woo plugin can only update feed profiles created by Woo plugin.

**Comment by ecgan** [comment]
@wjia88 @niketpins , this is similar to the issue I created previously, which seems to be fixed in the [1.0.0-beta.2 release](https://github.com/woocommerce/pinterest-for-woocommerce/releases/tag/1.0.0-beta.2):

- https://github.com/woocommerce/pinterest-for-woocommerce/issues/186

> **Changes required:**
> 
> 1. Error logging : Can we change the error logging to log message_detail and message both?

I believe we already have that, you do have to first enable debug logs in the Pinterest plugin settings though. You can see an example of that detailed logging in my https://github.com/woocommerce/pinterest-for-woocommerce/issues/186#issuecomment-904920460.

So, I suppose this issue can be closed?

**Comment by ghost** [comment]
Looked at the code again. It was fixed in beta.2 with commit https://github.com/woocommerce/pinterest-for-woocommerce/commit/a2b8fe20d7b79cc2d09e056013b0f10a9c678dd0

However in register_feed we are trying to find feed profiles created by Woo plugin. register_feed code can be simplified by using `/v3/catalogs/<merchant>/feed_profiles/` api which returns all feed profiles for a merchant and includes which feed profiles were created by Woo. will include api documentation in v2 as part of multi-feed effort. 

We can probably label this issue as tech debt and needs documentation.

**Comment by findingsimple** [comment]
I've created a follow up to https://github.com/woocommerce/pinterest-for-woocommerce/issues/211#issuecomment-932209153 over at https://github.com/woocommerce/pinterest-for-woocommerce/issues/223 so that it doesn't get lost in the comments here and will close as the original issues has been resolved.
