### ISSUE TITLE
Add special qualifiers in tags to help identify events coming specifically via integrations

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#393]
### Describe the bug:

we have special qualifiers added to the `partnerData`. This is to help us identify events coming specifically via integrations.

### Steps to reproduce:

1. Trigger pinterest tag by loading the website or trigger tag event by performing action such as Add to Cart

### Expected behavior:
woocommerce needs to sent as data payload without errors

### Actual behavior:
Currently not sent

### Additional details:

An example of an event  implementation in pintrk code
pintrk('load', <tag id>, {"np": "woocommerce"})  OR
pintrk('track', 'checkout', {"np": "woocommerce"})

https://help.pinterest.com/en/business/article/pinterest-tag-parameters-and-cookies
It is recommended to store {"np": "woocommerce"} in pd (partnerdata). See the screenshot below for an example.

![image](https://user-images.githubusercontent.com/1510328/158650848-288519b7-490b-4eca-9fa4-742b093d9bb9.png)

**Comment by budzanowski** [comment]
@adarshakb

I can't force this thing to work using the examples. The tag was being added to the `ed` section and not `pd`.
I did manage to get the expected result though in a quite different way. I have analyzed what happens when `pintrk` is called and it looks like one can add the additional partner data to `window.pintrk.partnerData` script will check for that and add it if it will be detected. Please see https://github.com/woocommerce/pinterest-for-woocommerce/pull/404 for code changes.

Is there a more canonic way of doing this?

**Comment by adarshakb** [comment]
@budzanowski - did you try to do this 

pintrk('load', <tag id>, {"np": "woocommerce"})  **Notice the event type to be load** - Adding np this way will add the np to all all further events triggered on that page

load should be called before other events. After that trigger an event like pageVisit.

That would be preferred method


However an alternative is we can add to ALL event triggers in any page like so - pintrk('EVENT', EVENT_TYPE, {"np": "woocommerce"}) -  this will add to ED (event data and NOT partner data - which as its self describing, wont persist across different events)

**Comment by budzanowski** [comment]
Yeah, that worked. I did not understand the original suggestion. I have tried to add this to separate events. PR updated.

**Comment by adarshakb** [comment]
Thank you!
