### ISSUE TITLE
Feed url might have spaces or any invalid characters

### ISSUE THREAD

**Issue by garo9521** [woocommerce/pinterest-for-woocommerce#834]
### Describe the bug:
Pinterest detected an error trying to create a URI object from the feed url given by WooCommerce app, this feed url contains a space, this is the one we're receiving `https://glorianneljubichdesign.com /wp-content/uploads/pinterest-for-woocommerce-fdeCDT.xml` we detect as a invalid url if they contain a space (it might be a tab character).

### Steps to reproduce:

1. This URL is provided to Pinterest API by WooCommerce app.

### Expected behavior:

could you add a trim function to remove spaces or any invalid character in the url?

### Actual behavior:

Sending a url with a space `https://glorianneljubichdesign.com /wp-content/uploads/pinterest-for-woocommerce-fdeCDT.xml`

### Additional details:

This is a issue from Pinterest, we could discuss this in our Slack channel.

**Comment by budzanowski** [comment]
This case suggests a deeper problem with the site configuration. The site configured URL contains a space - but it should not. The way we capture the location of the file directory is the canonical way. We do it via `wp_get_upload_dir` function.

https://github.com/woocommerce/pinterest-for-woocommerce/blob/bac648721e35084bf13d80d3ef112fd391a500a1/src/LocalFeedConfigs.php#L82-L83

> Expected behavior:
could you add a trim function to remove spaces or any invalid character in the url?

I don't think that we should trim here because even after trimming we will not know if this is the correct URL. We should detect the empty space, log an error, and aboard. We can also add a message to the merchant in the UI that we have detected this problem and ask them to fix this.

@message-dimke what do you think?

The alternative is to wait and do nothing - this is so far the first time we have seen such error and as I have mentioned this would mean a general configuration problem on the merchant side. This could have other consequences like wrong other URLs that are present in the XML file. We could skip it for now and revisit if we will have other signals about this.

@garo9521 what do you think?

**Comment by message-dimke** [comment]
I agree with @budzanowski in regards we should not fix that particular place by trimming or detecting and removing any characters from the path. If there is something wrong with a website configuration it must fail all the places for consistency.

I can see there is also a possibility to have `upload_dir` filter messing with the path somewhere.

**Comment by kaushikasomaiya** [comment]
User reached out on ticket 7210123-zen 

Figured out their `/wp-admin/options-general.php` area likely had Site URL and WP URL with a "tab" character at the end. (or perhaps something modified the values in DB directly)

Copied plain URL and pasted into both input boxes, pressed Save settings which resolved the issue.

**Comment by budzanowski** [comment]
I am closing this for now as the consensus is that we should not trim the value.
