### ISSUE TITLE
Could not fetch account status. [There was a previous error trying to create or update merchant.]

### ISSUE THREAD

**Issue by cbnsingram** [woocommerce/pinterest-for-woocommerce#846]
### Describe the bug:
I get this message at the top of the application's screen "Could not fetch account status. [There was a previous error trying to create or update merchant.]"

### Steps to reproduce:

1. Installed the plugin and successfully linked it to my pinterest business account
2. 
3. 

### Expected behavior:

Did not expect to see this error and am unsure what this will mean when I attempt to continue using the app.
### Actual behavior:

I get this message at the top of the application's screen "Could not fetch account status. [There was a previous error trying to create or update merchant.]"  All other "boxes" seem to be checked correctly
### Additional details:

A week or so ago I started the process of becoming a verified pinterest merchant but could not complete the process due to the short time my site and account have been online.

**Comment by budzanowski** [comment]
Hi @cbnsingram,

Please try accessing the service again after an hour since the error message is cached for that duration.

If the error continues beyond an hour, kindly reach out to our technical support. Our issue tracker isn't used for support purposes. Contact our Happiness Engineers for help at: https://woo.com/document/how-to-get-help/#questions-and-support

Should this be a bug, we'll open a dedicated Issue for it.

Best Regards,
Bartosz
